name: Playwright

on:
  push:
    branches:
      - main
    paths:
      - 'packages/css/src/**'
      - 'package-lock.json'
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Node
        uses: actions/setup-node@v4.3.0
        with:
          node-version: '24.11.1'
      - name: Install Dependencies
        run: npm ci
      - name: Setup JSX WASM binding
        run: npm run setup:jsx-wasm
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium webkit
      - name: Run Playwright
        run: npm run test:e2e
      - name: Upload Playwright artifacts
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: playwright-artifacts
          path: |
            packages/playwright/test-results
            packages/playwright/playwright-report
          if-no-files-found: ignore
          retention-days: 7
